---
title: "W01-29-Substetting - Lists"
author: "Lluis Calvo"
date: "1/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Substting - Lists

## Substting - Lists

```{r}

# List creation:
#    First element: foo, a list of integers (4 elements)
#    Second element: bar, a list of numeric (1 element)
x <- list(foo = 1:4, bar = 0.6)

# Single bracket: Retrieve first element as the same class of original, list
x[1]

class(x[1])

# Double bracket: Retrieve firs element as his own class, integer
x[[1]]

class(x[[1]])

# With single bracket we get a list with a sequence
# With double bracket we get just the sequence


# $ access: To get the element associated with the name after $
x$bar

# We can use double bracket operator with a string, same as previous example.
x[["bar"]]


# We can use simple bracket operator with a string, then we get a list.
x["bar"]

class(x[["foo"]])

class(x["foo"])

```


```{r}

# if we want to extract multiple elements of a list, then we need to use
# the single bracket operator

x <- list(foo = 1:4, bar = 0.6, baz = "hello")

x[c(1, 3)]


```
```{r}
# The [[ operator can be used with computed indices; · can oly be used with leteral names

x <- list(foo = 1:4, bar = 0.6, baz = "hello")

name <- "foo"

x[[name]]  # computed index for 'foo'

x$name     # element 'name' doesn't exist!

x$foo

```

## Subsetting Nested Elements of a List

The [[ can take an integer sequence.

```{r}

x <- list(a = list(10, 12, 14), b = c(3.14,2.81))

# two equivalent ways to extract third element of first list
x[[c(1,3)]]

x[[1]][[3]]

# We can also get the second element of first list
x[[c(1,2)]]

```

